### ISSUE TITLE
Unhandled exception and undefined unpipe method when closing ReadStream created by webtorrent using createReadStream passed to fluent-ffmpeg

### ISSUE THREAD

**Issue by James4Ever0** [mafintosh/streamx#71]
[Related issue](https://github.com/webtorrent/webtorrent/issues/2464) in webtorrent

Enviorments:

streamx 2.13.2
webtorrent 2.0.1
macOS Monterey 12.5
Node.js v18.11.0
npm 8.19.2

When running following code:

```javascript
var torrentPath="/Users/jamesbrown/Downloads/anime_download/[Kamigami&VCB-Studio] Yahari Ore no Seishun Lovecome wa Machigatte Iru. [Ma10p_1080p].torrent"

var selectedFilePath="[Kamigami&VCB-Studio] Yahari Ore no Seishun Lovecome wa Machigatte Iru. [Ma10p_1080p]/SPs/[Kamigami&VCB-Studio] Yahari Ore no Seishun Lovecome wa Machigatte Iru. [CM01][Ma10p_1080p][x265_flac].mkv"

import ffmpeg from 'fluent-ffmpeg'
import WebTorrent from 'webtorrent'

console.log("WEBTORRENT OBJECT?",WebTorrent)
const client=new WebTorrent({dht: true}) 

client.add(torrentPath, torrent => {
    var selectedFile=torrent.files.find(file => {
        return file.path==selectedFilePath
    })

    var stream=selectedFile.createReadStream() 
// reading from local filesystem works.
    // var stream = fs.createReadStream("/Users/jamesbrown/Downloads/anime_download/[Sakurato] Onii-chan wa Oshimai! [01][AVC-8bit 1080p AAC][CHT].mp4")


     ffmpeg.ffprobe(stream,(err,data) => {
         if(err) {
             console.log("FFPROBE ERROR:",err)
         } else {
             console.log("FFPROBE METADATA:",data)
         }
     process.exit()
     })
})
```

It will raise exceptions like:

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
Emitted 'error' event on Readable instance at:
    at ReadableState.afterDestroy (/opt/homebrew/lib/node_modules/webtorrent/node_modules/streamx/index.js:449:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v18.11.0
```

If I comment out the line of `/opt/homebrew/lib/node_modules/webtorrent/node_modules/streamx/index.js:449:19` which is `if (err) stream.emit('error', err)`, I sometimes get another exception (it vanishes overnight, can't explain), but sometimes get metadata as expected.

The exception:

```
/opt/homebrew/lib/node_modules/fluent-ffmpeg/lib/ffprobe.js:169
            input.source.unpipe(ffprobe.stdin);
                         ^

TypeError: input.source.unpipe is not a function
    at Socket.<anonymous> (/opt/homebrew/lib/node_modules/fluent-ffmpeg/lib/ffprobe.js:169:26)
    at Socket.emit (node:events:525:35)
    at Pipe.<anonymous> (node:net:313:12)
```

I fix the issue by:

```javascript
// stream is created using createReadStream
    stream.unpipe = (nodeStream) => {} //doing nothing?
    stream.on('error',function(err) {
        console.log('STREAM ERROR?',err);
        // just ignore it?
    })
```

I think there are better ways of fixing this issue, like not emitting this 'error' message at the first place (by passing configuration when constructing?), or adapting to any way `webtorrent` and `fluent-ffmpeg` use `streamx` which is considered as normal, or [implementing "unpipe" method](https://github.com/mafintosh/streamx/pull/64).

Update: the above fix only works for 'ffprobe' but not for general 'ffmpeg' code.

**Comment by mafintosh** [comment]
Thats how streamx works, the error is because the module you are using is not error handling the stream. Open an issue there.

unpipe is to me, 99.9% of the time an anti pattern. We are considering adding it, for compat, but haven’t heard a proper usecase yet.

**Comment by ThaUnknown** [comment]
@mafintosh honestly compat alone might be worth it as libraries which consume streams without importing readable-stream or stream exist
